### ISSUE TITLE
Handle multiple LoD

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#12]
Test data: Helsinki

In case of a multi-lod CityGML, the the LoD1 CityObjects are read as their type is (eg. Building, Road etc). But for LoD2 CityObjects, a new feature type is created per semantic surface (eg. RoofSurface, WallSurface etc.). I don't really like this approach. 

![image](https://user-images.githubusercontent.com/7190603/68953532-65ba9d00-07c2-11ea-866a-669de2c705c5.png)

Ideally, the feature types in FME == CityObject types, and not semantic surface types. 

At the moment I would prefer to give the option to the user to select the desired LoD when the reader is created. This would require to scan the whole file for multiple geometries for each CityObject. But anyway we are doing a full-scan on the geometries for creating the reader already. What do you think @hugoledoux and @KevinWiebe ?

**Comment by hugoledoux** [comment]
I fully agree with you: one CO == one FME-feature.

and yes user selecting the LoD is best, she can then read twice and manage herself 2 LoDs if she wants to (I guess?).

**Comment by KevinWiebe** [comment]
Yes, handling multiple geometries is kind of awkward.
FME has several formats that have these, and we have a few options on
what is possible.
As said before, it is probably a good idea to look at the CityGML reading
of similar data and see how that is read in FME.  This is probably a good
choice.

-Kevin-
