### ISSUE TITLE
Read textures

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#13]
See https://github.com/safesoftware/fme-CityJSON/blob/c203e92bd06a9e6c0cb25a7fb7be8c182a63675e/fmecityjson/fmecityjsonreader.cpp#L271-L341

And: https://github.com/safesoftware/fme-CityJSON/blob/c203e92bd06a9e6c0cb25a7fb7be8c182a63675e/fmecityjson/fmecityjsonreader.cpp#L346-L350

**Comment by KevinWiebe** [comment]
I think this has been fixed now.
