### ISSUE TITLE
Handle file-level metadata

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#19]
Some metadata is stored on the file level, not on object level. Ideally we would be able to retain this information and extend, change it in fme.

https://www.cityjson.org/specs/1.0.1/#metadata

**Comment by KevinWiebe** [comment]
There are a few options on how to deal with "metadata" at a dataset level,
but often we have found readers put out a single Metadata feature (with a
IFMENull Geometry maybe) that contains this information.
I'm not sure what CityGML does... but we could check.

-Kevin-
