### ISSUE TITLE
Writer with Feature Type Definition: "Import from Dataset" crashes FME when given minimum valid CityJSON

### ISSUE THREAD

**Issue by keithsorenson** [safesoftware/fme-CityJSON#27]
b20148 of FME Workbench crashes when the CityJSON Writer has its Feature Type Definition set to "Import from Dataset..", and the parameter is set to a minimum valid CityJSON file.  Readable CityJSON that contains City Objects will generate a Writer.  Non-city JSON is rejected with an error message, but a file with only `{"CityObjects":{},"type":"CityJSON","version":"1.0","vertices":[]}` causes FME to crash.

When I renamed the schema donor file "min_valid.json", I was briefly able to generate an error message instead of a crash, but when I test again, I reliably see the crash when attempting to import a schema from any minimal CityJSON file.

Testing on Win10 x64.  No apparent FME processes left over in task manager.

**Comment by hugoledoux** [comment]
I can indeed reproduce this bug.

@KevinWiebe I have no idea how to deal with this! Help from FME staff please...

**Comment by KevinWiebe** [comment]
I hope this is fixed by pull request 37

**Comment by hugoledoux** [comment]
It is.
