### ISSUE TITLE
shouldn't the reader/write be called "CITYJSON"?

### ISSUE THREAD

**Issue by hugoledoux** [safesoftware/fme-CityJSON#28]
and not "FMECITYJSON"? 

That would be inline with "CITYGML"  and the others, and I think the users know they are using FME, innit?

@KevinWiebe : I don,t want to mess your whole compilation so I didn't make that change myself...

**Comment by KevinWiebe** [comment]
You are probably right here.
I'll rename a few things.  I'll leave the names of the actual .cpp and .h files, as they are not really that important, but it will improve the way it looks inside FME, etc. to users.

**Comment by KevinWiebe** [comment]
Note that existing workspaces will probably stop working, as the format name has now officially changed.
