### ISSUE TITLE
Format/Schema/Metafile review and action items

### ISSUE THREAD

**Issue by KevinWiebe** [safesoftware/fme-CityJSON#40]
For all readers in FME, there is a relationship between the things listed in the metafile (cityjson.fmf), the schema features the reader produces (for a given dataset), and the data features the reader produces (for a given dataset).  This is a somewhat delicate balance, in that all 3 must be in harmony for the FME infrastructure as a whole to work smoothly and not have bugs down the line.

In this issue I am looking at some aspects where the things must align:

The issue here is that when pointed at a specific dataset, normally reading it (ie. in the Data Inspector) will produce "data features" that have a set of FeatureTypes.  For each of those FeatureTypes, the data features may have a variety of attributes and geometries.  When calling "readSchema()" on the reader with the same dataset, the schema features returned must *match* the data features that would be read.  I will define *match* below.

- A) There must be one schema feature returned for every FeatureType of data feature that _might_ be read.  Note that more FeatureTypes for schemas than actual data features is OK.  That is, if a data feature of a FeatureType is read, a schema feature of that matching FeatureType must have also been produced.  But it is OK to have readSchema() produce some FeatureTypes that read() doesn't actually produce any data features for.  readSchema() must produce a superset of all possible FeatureTypes that read() could produce.

-  B) The attributes listed on the schema features *should* be a superset of the attributes that might exist on data features of that FeatureType.  (In some formats this is too expensive, so it is not done 100% correctly, but there is pain down the line.)  Note that the data features do not need to have all the attributes listed on the schema for that FeatureType, but all the attributes they do have (except for ones that start with "fme_") should be listed on the appropriate schema feature.  Again a superset is on the schema feature.

-  C) The attribute Types listed on the schema feature should try to match the actual types of the values on the data features.  (The Types listed on the schema features are those in the left column of the ATTR_TYPE_MAP setting in the cityjson.fmf metafile.)

-  D) The geometries listed on the schema feature (geometry{0}, geometry{1}, etc.) should be a superset of all geometries that may be on data features read for that feature type. (The values for these geoemetry{} listings on the schema features are those in the left column of the GEOM_MAP settings in the cityjson.fmf metafile.)

-  E) *if* the metafile contains the line GENERICIZE_GEOMTYPE_ATTR_NAME, then every data feature that comes out must have an attribute with that specified name.  In this case, it is defined as `cityjson_type', so every data feature must have an attribute with that name, and the value must be one of those in the left column of the GEOM_MAP settings in the cityjson.fmf metafile.

OK, let's take a look at one example, and see how the cityjson format behaves with the "zurich_subset.json" file, from the example files.  What schema features will it produce from readSchema()?  What data features will it produce from read()?  Do they adhere to the rules above?  (You can add a line of code to log the features just before you return them, in both methods.  ex. gLogFile->logFeature(feature, FME_WARN); )

Here is what comes out of read(), one example for each FeatureType:
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `Metadata'
Attribute(string): `fme_type' has value `fme_no_geom'
Attribute(string): `geographicalExtent' has value `[2683498.64,1247828.0489999999,407.0,2683515.973,1247861.068,431.682]'
Attribute(string): `presentLoDs' has value `{"2.0":145865}'
Attribute(string): `referenceSystem' has value `urn:ogc:def:crs:EPSG::2056'
Geometry Type: Unknown (0)
Number of Coordinates: 0 -- Coordinate System: `'
===========================================================================+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `Building'
Attribute(string)        : `FileCreationDate' has value `2012-03-22'
Attribute(32 bit integer): `GebaeudeStatus' has value `1'
Attribute(string)        : `Herkunft' has value `EE_LB_2007'
Attribute(32 bit integer): `QualitaetStatus' has value `1'
Attribute(32 bit integer): `Region' has value `8'
Attribute(string)        : `cityjson_children{0}' has value `UUID_498cb034-5aa4-435a-b448-9ae304a6c332'
Attribute(string)        : `cityjson_children{10}' has value `UUID_c7b8ecbc-8fa4-46da-a256-159b0c856652'
Attribute(string)        : `cityjson_children{11}' has value `UUID_188357fa-6f0f-4ccb-a819-116e13f6fe06'
Attribute(string)        : `cityjson_children{1}' has value `UUID_356d4262-0eb3-4b42-8c24-26707016f61a'
Attribute(string)        : `cityjson_children{2}' has value `UUID_652784c5-bbbb-40e5-8705-0598ed0c2f51'
Attribute(string)        : `cityjson_children{3}' has value `UUID_ff5b3d71-726f-4b9d-96d0-23fc217a9da8'
Attribute(string)        : `cityjson_children{4}' has value `UUID_22a1b09e-18e6-4b0b-b573-3c4d41f1ebbe'
Attribute(string)        : `cityjson_children{5}' has value `UUID_a0285dd9-dd99-446d-8610-90493bcdaba6'
Attribute(string)        : `cityjson_children{6}' has value `UUID_734f2d11-3ebb-4143-89bf-82fa6b0d8ccf'
Attribute(string)        : `cityjson_children{7}' has value `UUID_b3e8ca86-f796-45e9-b71d-38d9ae2af150'
Attribute(string)        : `cityjson_children{8}' has value `UUID_542f4852-077d-4b30-9bd7-dd39bb910fa3'
Attribute(string)        : `cityjson_children{9}' has value `UUID_de5e8cd8-2ac1-4deb-b08b-6389c87985aa'
Attribute(string)        : `class' has value `BB06'
Attribute(string)        : `creationDate' has value `2017-01-23'
Attribute(string)        : `fid' has value `UUID_07960081-c509-4e09-aadf-36f66852b4c0'
Attribute(string)        : `fme_type' has value `fme_no_geom'
Geometry Type: Unknown (0)
Number of Coordinates: 0 -- Coordinate System: `EPSG:2056'
===========================================================================
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `BuildingPart'
Attribute(32 bit integer): `Geomtype' has value `2'
Attribute(string)        : `cityjson_parents{0}' has value `UUID_07960081-c509-4e09-aadf-36f66852b4c0'
Attribute(string)        : `creationDate' has value `2017-01-23'
Attribute(string)        : `fid' has value `UUID_188357fa-6f0f-4ccb-a819-116e13f6fe06'
Attribute(string)        : `fme_geometry' has value `fme_aggregate'
Attribute(string)        : `fme_type' has value `fme_surface'
Coordinate System: `EPSG:2056'
Geometry Type: IFMEMultiSurface
Number of Geometry Traits: 1
GeometryTrait(string): `cityjson_lod' has value `2'
Front Appearance Reference: `<inherited_or_default_appearance>'
Back Appearance Reference: `<inherited_or_default_appearance>'
Number of Surfaces: 6
--------------------------------------
...
===========================================================================
```

Now when the reader is asked for "schema features", here is what comes out:
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `Metadata'
Attribute(string): `fme_geometry{0}' has value `cityjson_text'
Attribute(string): `geographicalExtent' has value `string'
Attribute(string): `presentLoDs' has value `string'
Attribute(string): `referenceSystem' has value `string'
Attribute: `geographicalExtent' is sequenced
Attribute: `presentLoDs' is sequenced
Attribute: `referenceSystem' is sequenced
Geometry Type: Unknown (0)
Number of Coordinates: 0 -- Coordinate System: `'
===========================================================================+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `Building'
Attribute(string): `FileCreationDate' has value `string'
Attribute(string): `GebaeudeStatus' has value `int32'
Attribute(string): `Herkunft' has value `string'
Attribute(string): `QualitaetStatus' has value `int32'
Attribute(string): `Region' has value `int32'
Attribute(string): `class' has value `string'
Attribute(string): `creationDate' has value `string'
Attribute(string): `fid' has value `string'
Attribute(string): `fme_geometry{0}' has value `cityjson_null'
Attribute: `fid' is sequenced
Attribute: `FileCreationDate' is sequenced
Attribute: `GebaeudeStatus' is sequenced
Attribute: `Herkunft' is sequenced
Attribute: `QualitaetStatus' is sequenced
Attribute: `Region' is sequenced
Attribute: `class' is sequenced
Attribute: `creationDate' is sequenced
Geometry Type: Unknown (0)
Number of Coordinates: 0 -- Coordinate System: `'
===========================================================================
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Feature Type: `BuildingPart'
Attribute(string): `Geomtype' has value `int32'
Attribute(string): `creationDate' has value `string'
Attribute(string): `fid' has value `string'
Attribute(string): `fme_geometry{0}' has value `cityjson_multisurface'
Attribute: `fid' is sequenced
Attribute: `Geomtype' is sequenced
Attribute: `creationDate' is sequenced
Geometry Type: Unknown (0)
Number of Coordinates: 0 -- Coordinate System: `'
===========================================================================
```

Let's analyze the results.  How did we do?

- A) We did have a schema feature produced for every FeatureType of data produced.  Yay!  No problems.
- B) For the most part, all attributes on the data features were present on the schema feature of the matching FeatureType.  Yay!  The only problem was "list attributes", that had {} in them.  These were not listed.
  - For example, in the 'BuildingPart' FeatureType, the data feature had a 'cityjson_parents{0}' attribute, but this was not on the schema feature.  In this case, you simply need to put one representative attribute on the schema feature, not all of them.  So the attribute 'cityjson_parents{}' should be on the schema feature.  (Note that it is just {} with no number inside.)
- C) I didn't take a close look, but most attribute types seem to match OK.  Maybe the 'creationDate' type attributes could have a type of 'date' instead of 'string'...
- D) This doesn't look so good.  
  - I see the data feature with the 'Metadata' FeatureType has a NULL geometry, but that is not listed on the schema feature for that feature type.  Only 'fme_geometry{0}' has value 'cityjson_text'.  The schema feature should at least list 'cityjson_null' as one of the fme_geometry{} values.
  - 'Building' Feature type is OK.  The data feature and schema feature match, with 'cityjson_null'.  But I'd be cautious of this, because maybe some other files have solids or something?  If so, then the schema feature maybe should have fme_geometry{1} with cityjson_solid or something in those cases?  Maybe check different input files.  But maybe this is all OK and I don't understand the format enough.
  - 'BuildingPart' looks good.  It has a multisurface data feature and multisurface on the schema, so it matches.
- E) None of the data features produced have the required cityjson_type attribute.  There are two solutions to this:
  - leave most things as they are, but just add this attribute (with the correct value) to all data features that are produced.
  - re-think if this format needs this attribute at all.  If not, then update the metafile in a way that indicates it is not needed.  More complicated formats require this attribute, but simple ones do not.
  -> Hmmm.  I just typed in a very long question to you about which case this might be, but I've convinced myself it is the second case.  We should just get rid of cityjson_type and never use it, I think.  If you agree, I'll make those changes and push up that change.  If we're wrong, I can go the other way.  Sound good?

Conclusion and action items:
- There is a bit of work that needs to be done for B and D.  (And maybe C?)  I'm hoping folks at the Delft end can patch those up.
- There is some work that needs to be done for E.  If you're OK with it, I'll patch this up from my end.  Sound good @hugoledoux ?

**Comment by hugoledoux** [comment]
thanks for that short (!) explanation :)

I think as a general rule you can just do what you see necessary, we just want to have CityJSON in FME and not break things in doing so. You know better, fix where you see fit.

Two comments:

1. is `cityjson_type` mandatory? I'd say no, this is the same as the feature type, no?
2. the feature 'Metadata' is a special case. It's not a feature/city-object of CityJSON but since we like metadata (who doesn't?) we wanted to be able to read the metadata. @balazsdukai thought of having a feature without geometry, I am not sure he discussed this with you. Is this the "best" way to do so? If not, then let us know what it would be.

For metadata, notice that the writer doesn't write the feature yet... The main reason is that I don't know how to update metadata for a given set of features yet. Or is it possible? With other formats that require metadata, how does FME handle this? (probably another issue on this is necessary here!)

**Comment by balazsdukai** [comment]
Regarding the 'Metadata' feature. The metadata in CityJSON is just a regular JSON object (json terminology), thus I thought it's the best to read it so. Or at least that was my attempt in https://github.com/safesoftware/fme-CityJSON/pull/24

Ideally it wouldn't refer to any kind of geometry at all, and it would be read as a regular json reader reads stuff. Or in the extreme case, all the 'Metadata' would be replicated on each feature (but that's a no no in my opinion).

Then in the workbench the user can update the values of the individual elements of the Metadata feature, using the json-transformers of FME. Or just pipe it directly to the output (if thats also cityjson).

**Comment by KevinWiebe** [comment]
I have addressed a few issues in pull request #42 .
- I've removed the use of cityjson_type.  This format is not complex enough to require it.  Using FeatureTypes and different Geometry types is sufficient.  All is simpler now.
- I've allowed the writer to accept input of a Metadata feature.  For now it just ignores it, but it is a template on what you might want to do with it in the future, @balazsdukai 

To comment specifically on Metadata, I think your decisions are well in line with what a lot of other FME formats have done.  
  - The reader will produce one "metadata" type of feature.  Often it will have a IFMENull geometry, or maybe a box geometry, which is the extents of the dataset.  
  - Workebench users can pick apart that metadata feature and use it however they wish.  They can massage that data into a way that some other writer might want it, maybe in a similar "metadata" type feature the writer expects.  (It is not expected that metadata info from one format will slide seamlessly into a writer of a different format.)
  - If CityJSON is also the writer, now the writer will not be surprised if it gets a Metadata FeatureType sent into it.  It can pick it apart in the writer code and do whatever actions it likes.  (Probably it would not use the bounds, as it would need to recalculate that itself.  The data features sent into the writer may not be the same ones that came out of the reader, so the bounds is likely out of date.)


So my recent code change fixes some of D and all of E.  There is still work on A, D (and maybe C?) left.

**Comment by balazsdukai** [comment]
+ C) I tried to remove the irrelevant types from the `ATTR_TYPE_MAP`, but then FME complains that,

```
Attribute type 'fme_char' not found in ATTR_TYPE_MAP. Trying 'fme_int8'
Attribute type 'fme_int8' not found in ATTR_TYPE_MAP. Trying 'fme_int16'
``` 
so I left the metafile as it is. This is what I wanted to have:

```
! --------------------------------------------------------------------------------
! Define the mappings of the attribute types.
! --------------------------------------------------------------------------------
 ATTR_TYPE_MAP                                                     \
                string                  fme_buffer                 \
                string                  fme_binarybuffer           \
                string                  fme_xml                    \
                string                  fme_json                   \
                real64                  fme_real64                 \
                int32                   fme_int32                  \
                logical                 fme_boolean                
```

**Comment by KevinWiebe** [comment]
I think for the most part, A) is pretty good.  I can't see any glaring issues here.  Might be a few details we can clean up later, if they crop up.  But for this issue, let's just say A) now looks good.

I just cleaned up C) in the metafile for you.  It all looks ok now.  I can't see how someone who does not work at Safe has much hope of figuring out how to do that part, so I just did it.
(It had to be fixed not by removing lines, but by duplicating some entries.  And the order of these lines is also important.)  Just update your metafile to the latest version and you'll get the good one.

For D) I was just looking at the reader code.  It looks OK to me now, as I've fixed a bunch of it up.  I now realize that "building" features really do have no geometry, so when the schema says it has 'cityjson_null', then it is actually the truth.  (I had thought it would be a solid or something, given the name "building".)  So it all looks good as well!

**Comment by hugoledoux** [comment]
Yes, I am against this but we followed the CityGML data model on that one: a Building (or any other city object) can have an empty geometry. In this case (I assume it's the file from Den Haag I sent you?) the geometries are in the 2 children of the building (BuildingPart). Super annoying to deal with, but this is it.

In CityGML, these BuildingParts are allowed to have children, which are allowed to have children, etc. In CityJSON we have one level only.

**Comment by KevinWiebe** [comment]
I think for the most part all issues listed here are dealt with.  We can probably close this issue and open new clean ones for any details we may have missed.
