### ISSUE TITLE
Reader log doesn't recognize when the LoD parameter is set

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#41]
Doesn't matter what is specified for the LoD paramter, the Reader always says that `There are multiple Levels of Detail present in the CityJSON data: 1, 2 
No value is set for the 'CityJSON Level of Detail' parameter. Defaulting to: 1` when the reader is created.

However, the actual reading is done correctly for each LoD.

**Comment by balazsdukai** [comment]
I did some further exploration and it seems that `fetchWithPrefix` doesn't / can't read the parameter when the Reader is created in the workspace. So it returns false.
https://github.com/safesoftware/fme-CityJSON/blob/4c1f18eee7999290cb3fee7ebc04ed90959d3eb9/fmecityjson/fmecityjsonreader.cpp#L1262

After the Reader is created and the data is actually read, `fetchWithPrefix` is able to read the parameter correctly. I have no idea why is this, maybe @KevinWiebe ?

**Comment by KevinWiebe** [comment]
Yes, parameter fetching, etc. is slightly different when generating a new reader (when "readSchema()" will be called) and when running a reader already present in a workspace (when "read()" will be called).

For your case, when adding a new reader, the metafile needs another line at the top, which picks out which of the reader parameters it passes off to the reader at that time.

I've modified the metafile so the LOD setting is passed off now, and pushed up the changes.  You'll be able to use the same fetchWithPrefix to find it when you need to now.

https://github.com/safesoftware/fme-CityJSON/pull/51

**Comment by KevinWiebe** [comment]
I believe that pull request #49 probably fixes this, right?

**Comment by balazsdukai** [comment]
Yes. The issue will be closed automagically once the PR is merged (see https://github.blog/2013-01-22-closing-issues-via-commit-messages/ )
