### ISSUE TITLE
When the LoD parameter is set, all features are read, but some of them with NULL geometry

### ISSUE THREAD

**Issue by balazsdukai** [safesoftware/fme-CityJSON#50]
In case of a [multi-lod data](https://github.com/safesoftware/fme-CityJSON/blob/lod-handling/example_data/textures_building/csurface_buildings.json) when I set the LoD parameter to eg. 2, still all features are read from the file. The ones whose LoD does not match the parameter will get a NULL geometry, but the feature is created nevertheless, also the attributes are read.

When using the LoD parameter on the Reader, every feature should be ignored (not read) that doesn't have the required LoD.

**Comment by KevinWiebe** [comment]
I believe pull request #49 fixes this, right?

**Comment by balazsdukai** [comment]
Yes. The issue will be closed automagically once the PR is merged (see https://github.blog/2013-01-22-closing-issues-via-commit-messages/ )
