### ISSUE TITLE
CityJSON output not validating in cjio

### ISSUE THREAD

**Issue by KevinWiebe** [safesoftware/fme-CityJSON#58]
In the attached FME workspace template (created with b20238 x64) CityJSON Waterbody Objects are created which do not validate against cj.io (https://github.com/cityjson/cjio). It seems to me that CityJSON features which do not have further semantic surfaces are not allowed to have a NULL value in the type attribute. So with my workspace the following output (subset) is created which fails to validate:

```
"lod": 1.0,
    "semantics": {
        "surfaces": [ 

            null

         ],
        "values": [

             null

        ]
    },
"type": "Solid"

```
If I take out the first Null value, the validation checks out. If I use another Writer FeatureType like Terrain or Building this problem is also not present. In these FeatureTypes the Surfaces attribute is filled (or left blank) correctly.

[Create_WaterBody.zip](https://github.com/safesoftware/fme-CityJSON/files/5300457/Create_WaterBody.zip)

**Comment by hugoledoux** [comment]
hmmm, puzzled by this.

So if a Building doesn't have semantics then the property `"semantics"` doesn't get created, but for `"WaterBody"` yes?

**Comment by KevinWiebe** [comment]
Our testers here say:
"Upon testing the workspace, the null semantics property is created for both WaterBody and Building."

**Comment by KevinWiebe** [comment]
Fixed.
