### ISSUE TITLE
CityJSON Writer not writing string attributes for semantic surfaces

### ISSUE THREAD

**Issue by KevinWiebe** [safesoftware/fme-CityJSON#59]
From con terra:

According to the CityJSON specification it should be allowed that semantic surfaces have attributes, here is the respective passage from the manual:

A Semantics Surface is a JSON object representing the semantics of a surface, and may also represent other attributes of the surface (eg the slope of the roof or the solar potential)…. may have other attributes in the form of a JSON key-value pair, where the value must not be a JSON object (but a string/number/integer/boolean).

Which, if applied correctly, should look like this where slope, solar-potential and type-glass are user-defined attributes:

```
{
  "type": "RoofSurface",
  "slope": 16.4,
  "children": [2, 37],
  "solar-potential": 5
}
{
  "type": "Window",
  "parent": 2,
  "type-glass": "HR++"
}
```

However, when a string value trait is set with GeometryPropertySetter, the attribute won't be written out in the output json file, with error message `Unknown fetchMode provided for fetchFeatureTypes. No feature types will be returned` and warning message `Semantic Surface attribute type '12' is not allowed. ... Last line repeated 3 times ...`

A workspace template is attached to demonstrate the issue, along with the output and log file.

Reproduced in b20608 - WIN64 (The output generated from MacOS looks correct).

[FMEENGINE-66751.zip](https://github.com/safesoftware/fme-CityJSON/files/5300492/FMEENGINE-66751.zip)

**Comment by hugoledoux** [comment]
so it works in macOS but not Windows?

**Comment by KevinWiebe** [comment]
Was the same version run on mac and windows?  If different versions, that might explain why one worked and one did not.

**Comment by KevinWiebe** [comment]
The problem here was that strings were written out but _encoded_ strings were being dropped.  Now both are written out.

**Comment by KevinWiebe** [comment]
@hugoledoux The problem here was that strings were written out but encoded strings were being dropped. Now both are written out.
