### ISSUE TITLE
Can CityJSON have a geometry with BOTH a Texture and a Material attached?  If so, read this in correctly.

### ISSUE THREAD

**Issue by KevinWiebe** [safesoftware/fme-CityJSON#73]
I'm not sure what is possible in CityJSON, but FME does allow geometries to have BOTH a material and a texture attached to a single geometry at once.

It would be nice to have an attachment to this issue that has an example with both, to use for testing.

One we have that example, we can change the code to read them both in and attach them both correctly.

(Note: the code has TODO: issue 73: markers where this issue is present.)

**Comment by hugoledoux** [comment]
CityJSON would allow both textures and materials, and there can be many for one object.

Snippet coming soon, I'll fix something quickly

**Comment by KevinWiebe** [comment]
This has been completed.
