### ISSUE TITLE
Reader: Are CityJSON surfaces single sided or double sided?  Which kind of FME surfaces should be made?

### ISSUE THREAD

**Issue by KevinWiebe** [safesoftware/fme-CityJSON#74]
FME can store double sided, front sided, back sided, even zero sided surfaces.  What should be made in the CityJSON reader?
Really, it comes down to setting textures or materials (or "default" values for those) on the correct sides.
Currently the code make double sided FME Faces.
Note that in the FME Data Inspector it will show faces as transparent when viewed from a "side" that does not exist.

(Note: the code has TODO: issue 74: markers where this issue is present.)

**Comment by hugoledoux** [comment]
Hmmm, never thought of this to be honest.

I would say "front-sided" is enough: textures only on one side.

**Comment by KevinWiebe** [comment]
Done!
